FROM ubuntu:20.04

ENV LOGIN=
ENV HOST=
ENV PORT=18443
ENV PASSWORD=
ENV TZ=Europe/Moscow


RUN apt-get update && apt-get install curl -y && \
    curl https://filestore.fortinet.com/forticlient/downloads/FortiClientFullVPNInstaller_6.4.0.0851.deb -o FortiClientFullVPNInstaller_6.4.0.0851.deb && \
    apt-get install ./FortiClientFullVPNInstaller_6.4.0.0851.deb -y

#RUN curl https://filestore.fortinet.com/forticlient/downloads/FortiClientFullVPNInstaller_6.4.0.0851.deb -o FortiClientFullVPNInstaller_6.4.0.0851.deb
#RUN apt-get install ./FortiClientFullVPNInstaller_6.4.0.0851.deb -y

RUN apt-get update && \
    apt-get install -y -o APT::Install-Recommends=false -o APT::Install-Suggests=false \
    ca-certificates \
    iproute2 \
    expect && \

    rm -R FortiClientFullVPNInstaller_6.4.0.0851.deb && \
    apt-get -y remove curl && \
    apt-get clean -q &&  \
    apt-get -y autoremove --purge && \
    rm -rf /var/lib/apt/lists/*

#RUN rm -R FortiClientFullVPNInstaller_6.4.0.0851.deb && \
#    apt-get clean -q &&  \
#    apt-get -y autoremove --purge && \
#    rm -rf /var/lib/apt/lists/*

COPY start-connect.exp start-connect.exp

CMD expect start-connect.exp $HOST:$PORT $LOGIN $PASSWORD