FROM ubuntu:20.04

ENV TZ=Europe/Moscow

RUN apt-get update && apt-get -y install \
                                 python3 \
                                 python3-pip \
                                 screen \
                                 openfortivpn && apt-get clean -q && apt-get -y autoremove --purge

RUN pip3 install --no-cache --upgrade requests pymongo