#!/usr/bin/expect
set HOST [lindex $argv 0]
set LOGIN [lindex $argv 1]
set PASSWORD [lindex $argv 2]

#spawn /opt/forticlient/vpn  --server=$HOST --user=$LOGIN -p
spawn /opt/forticlient/vpn  --server='37.18.109.130:18443' --user=$LOGIN -p
expect "password:"
send "$PASSWORD\r"
#expect "Confirm (y/n) \[default=n\]:Confirm (y/n) \[default=n\]"
#expect "Confirm (y/n) \[default=n\]:Confirm (y/n) \[default=n\]:"
expect "Confirm (y/n)"
send "y\r"
interact
